name: Jailbreak3
main: me.cxom.jailbreak3.Jailbreak
version: 1.2.1
api-version: 1.13
description: Rendition 3 of the Minecraft minigame Jailbreak
depend: [MovementPlusPlus]
soft-depend: [ActionBarAPI]

commands:
  jailbreak:
    aliases: jb