name: Jailbreak3
main: me.cxom.jailbreak3.Jailbreak
version: 1.2.5.1
api-version: 1.15
description: Rendition 3 of the Minecraft minigame Jailbreak
depend: [ActionBarAPI, PunchTree-Minigames, MovementPlusPlus]

commands:
  jailbreak:
    aliases: jb